# 应用名称
spring:
  application:
    name: mqtt-demo
    # activeMq配置
  activemq:
    broker-url: tcp://192.168.3.62:61616
    # 消息模型 true：发布/订阅消息模型  false：点对点消息模型
  jms:
    pub-sub-domain: true

# 应用服务 WEB 访问端口
server:
  port: 9999

# Mqtt配置
mqtt:
  urls: tcp://192.168.3.62:1883
  username: one
  password: ok
  client:
    id: ${random.value}
  topic: one,two
