# 应用名称
spring:
  application:
    name: mqtt-demo
# 应用服务 WEB 访问端口
server:
  port: 8080

# Mqtt配置
mqtt:
  urls: tcp://localhost:5555
  username: one
  password: ok
  client:
    id: ${random.value}
  topic: one,two


